### ISSUE TITLE
validation loss computation with sg_reuse()

### ISSUE THREAD

**Issue by cyu0913** [buriburisuri/ByteNet#1]
I'm interested in monitoring validation loss during training. I tried to use sg_reuse() function as in the examples of your sugartensor repository. But it seems a little difficult to do this in Bytenet, maybe due to the  concatenation (enc = enc.sg_concat(target=y_src.sg_lookup(emb=emb_y))) ? 

Could you point me a way to calculation validation loss in Bytenet?

Many Thanks.

**Comment by buriburisuri** [comment]
@cyu0913 The sg_reuse() function is only for simple network.  A complex network like Bytenet, you should use the normal tensor flow way - All variables should be named precisely and reuse option on as following code:

```
    with tf.sg_context(name='test', act='relu', bn=True, reuse=True):
        res = (x
               .sg_conv(dim=64, size=4, stride=2, name='conv1')
               .sg_conv(dim=128, size=4, stride=2, name='conv2')
               .sg_flatten()
               .sg_dense(dim=10, act='linear', bn=False)
```

**Comment by cyu0913** [comment]
Thanks for the reply. I will try this.
